#!/usr/bin/env python
""" Simple Load Font Example
http://www.robodocs.info/roboFabDocs/source/howtos/world.html#openfont-path

This script open a UFO file from first argument.
note: $ pip install robofab
"""

import argparse, robofab
from robofab.world import RFont

parser = argparse.ArgumentParser()
parser.add_argument(
	"ufo", 
	help = "the UFO file to process"
)
parser.add_argument(
	"-v", "--verbose", 
	help = "increase output verbosity",
	action = "store_true"
)
args = parser.parse_args()


path = args.ufo

f = RFont(path)
print "The current font is {}".format(f.info.postscriptFullName)


# so now f is the name of a font object for the current font.

if f == None:
	# let's see what dialog can do, a warning
	print "You should open a font first, there's nothing to look at now!"
else:
	if args.verbose:
		# let's have a look at some of the attributes a RoboFab Font object has
		print "the number of glyphs:", len(f)
		# some of the attributes map straight to the FontLab Font class
		# We just straightened the camelCase here and there
		print "full name of this font:", f.info.postscriptFullName
		print 'ascender:', f.info.ascender
		print 'descender:', f.info.descender

print '-----'
print "list of glyph names:", f.keys()
