#!/usr/bin/env python2
""" Glyph Plot
UFO to DrawBot
Prints a glyph in drawbot path instructions
Usage:
$ ./UFO-drawBot file.ufo glyphname > somedrawbotcode.py

"""


import numpy as np
import argparse, robofab, math, sys
from robofab.world import RFont

parser = argparse.ArgumentParser()
parser.add_argument(
	"ufo_in",
	help = "The ufo file to process"
)
parser.add_argument(
	"glyph",
	help = "The glyph to print for DrawBot"
)
parser.add_argument(
	"-v", "--verbose",
	help = "Increase output verbosity",
	action = "store_true"
)
args = parser.parse_args()

ufo_path   = args.ufo_in
glyph_name = args.glyph


def main():

	font = RFont(ufo_path)

	if font == None:
		print "You should open a font first, there's nothing to look at now!"
	else:
		print '#####'
		print "# Font:",font.info.postscriptFullName
		print '# Glyph:', glyph_name,'\n'
		if args.verbose:
			print "# The number of glyphs:", len(font)
			print "# Full name of this font:", font.info.postscriptFullName
			print '# Ascender:', font.info.ascender
			print '# Descender:', font.info.descender,'\n'
			print '# List of glyph names:', font.keys()
			print '#####\n'


	glyph = font[glyph_name]

	plotear_glifo(
		glyph,
		font
	)



# Subs

def plotear_glifo(
	self,
	font,
	offset = (0,0),
	scale = (1,1)
):
	for aPt in self[0].bPoints:
		print aPt
		print aPt.bcpIn, aPt.bcpOut, aPt.anchor

	CONTOURS = []
	for contour in self:

		CODIGOS = [] # para drawbot
		VERTS = []
		for point in contour.points:
			# Dirty fix for vertical offset
			pathVert      = ( point.x, point.y + 200 ) 
			pathResultado = tuple(
				( v1 + v2 ) * v3 for
				v1, v2, v3 in
				zip( pathVert, offset, scale )
			)
			VERTS.append( pathResultado );

			pathCode = pType2pCode[point.type]
			CODIGOS.append( pathCode )
		
		# drawBot path printing (raw aproach)
		print '# PATH', self.name, '#####'
		print 'newPath()'
		ctrlCounter = 0
		for index, vertice in enumerate(VERTS):
			if CODIGOS[index] == 3: 
				ctrlCounter += 1
			# curveOrder = curveCounter % 2 
			elif CODIGOS[index] == 4: # curva

				print pType2drawBotPath[CODIGOS[index]]+'('
				print '  ',repr( VERTS[index-2] )+', # ctrl pt 1'
				print '  ',repr( VERTS[index-1] )+', # ctrl pt 2'
				print '  ',vertice
				print ')'
			else:
				print pType2drawBotPath[CODIGOS[index]]+'('
				print '  ',vertice
				print ')'
		print 'closePath()'
		print 'drawPath()'
		print '# END #####\n'

	for component in self.components:
		componentName   = component._baseGlyph
		componentnGlyph = font[componentName]
		componentOffset = [
			( v1 + v2 ) for
			v1, v2, in
			zip( component._offset, offset )
		]
		componentScale  = [
			( v1 * v2 ) for
			v1, v2, in
			zip( component._scale, scale )
		]

		plotear_glifo(
			componentnGlyph,
			font,
			componentOffset,
			componentScale
		)

		if args.verbose:
			print vars(component)

pType2drawBotPath = {
		0: 'newPath',
		1: 'moveTo',
		2: 'lineTo',
		3: '',
		4: 'curveTo',
		79: 'closePath',
}
######
# robofab point type to matplotlib path code maping
# http://matplotlib.org/api/path_api.html

pType2pCode = {
	'stop' : 0,
	'move' : 1,
	'line' : 2,
	# 'offcurve': 3,
	'offcurve' : 3,
	'curve' : 4,
	'close' : 79,
}

main()
