#!/usr/bin/env python

# usage: $ python print-glyphs-fontforge.py "League-Gothic.ufo"
# http://i.liketightpants.net/and/programmatically-manipulating-typefaces

import fontforge
import sys

font = fontforge.open(sys.argv[1])

for glyph in font.glyphs():
    print glyph
